
// Testing request home
GET http://localhost:4000
###

// Testing request READ all students
GET http://localhost:4000/students
###

// Testing request READ single student
GET http://localhost:4000/student/6458425cf10424fe7c9bbf5a
###

// Testing request CREATE new student
POST http://localhost:4000/new-student
content-type: application/json

{
    "firstName": "Andres",
    "lastName": "Martinez",
    "age": 20,
    "phone": "4561238786",
    "email": "andres@andres.com",
    "address": "C/c n2",
    "degree": "Machanic",
    "university": "BYU IDAHO"
}
###

// Testing request UPDATE student
PUT http://localhost:4000/update-student/645a93fee47234469e6842bb
content-type: application/json

{
    "firstName": "Andres",
    "lastName": "Martinez Rivera",
    "age": 20,
    "phone": "4561278968",
    "email": "andres@andres2.com",
    "address": "C/c n2",
    "degree": "PSYCHOLOGY",
    "university": "BYU IDAHO"
}
###

// Testing request DELETE student
DELETE http://localhost:4000/delete-student/645a93fee47234469e6842bb




