
// Testing request home
GET http://localhost:4000/api
###

// Testing request all students
GET http://localhost:4000/api/students
###

// Testing request single student

GET http://localhost:4000/api/student/644d63117361f3bbfcdb9cbd
###

// Testing request create new student

POST http://localhost:4000/api/new-student
content-type: application/json

{
    "firstName": "Andres",
    "lastName": "Martinez",
    "age": "20",
    "phone": "456123789",
    "email": "andres@andres.com",
    "address": "C/c n2",
    "degree": "Machanic",
    "university": "BYU IDAHO"
}
###

// Testing request update student

PUT http://localhost:4000/api/update-student/644d822d3897d90c7afc47f0
content-type: application/json

{
    "firstname": "Andres ",
    "lastname": "Pendejo",
    "age": "20",
    "phone": "456123789",
    "email": "andres@andres2.com",
    "address": "C/c n2",
    "degree": "PSYCHOLOGY",
    "university": "BYU IDAHO"
}
###

// Testing request update student

DELETE http://localhost:4000/api/delete-student/644d81e33897d90c7afc47ee




