
// Testing request home
GET http://localhost:4000/api
###

// Testing request READ all students
GET http://localhost:4000/api/students
###

// Testing request READ single student
GET http://localhost:4000/api/student/6458425cf10424fe7c9bbf59
###

// Testing request CREATE new student
POST http://localhost:4000/api/new-student
content-type: application/json

{
    "firstName": "Andres",
    "lastName": "Martinez",
    "age": 20,
    "phone": "4561235786",
    "email": "andres@andres.com",
    "address": "C/c n2",
    "degree": "Machanic",
    "university": "BYU IDAHO"
}
###

// Testing request UPDATE student
PUT http://localhost:4000/api/update-student/64591c567b2879b317879dbe
content-type: application/json

{
    "firstName": "Andres",
    "lastName": "Martínez Rivera",
    "age": 20,
    "phone": "4561237898",
    "email": "andres@andres2.com",
    "address": "C/c n2",
    "degree": "PSYCHOLOGY",
    "university": "BYU IDAHO"
}
###

// Testing request DELETE student
DELETE http://localhost:4000/api/delete-student/64591c567b2879b317879dbe




